# -*- coding: utf-8 -*-
"""DataAugmentation_DSIM_Project_Monochannelsignal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1acG7X4F-fQzE4bpX33DaiWbqXM626Fr5
"""

!pip install audiomentations &> /dev/null
!pip install audiomentations[extras] &> /dev/null

# Library import
from google.colab import drive
from shutil import copytree, move

from audiomentations import Compose, TimeStretch, TimeMask, HighPassFilter, AddGaussianNoise, RoomSimulator
import soundfile as sf
import os
import random

import librosa

drive.mount('/content/gdrive')
copytree('gdrive/My Drive/DSIM_Project_Monochannelsignal/audios', 'audios')

path_audios = '/content/audios/'
path_augmented = '/content/audios-augmented/'
copytree(path_audios, path_augmented)

"""# **Data Augmentation**"""

# Defining the transformations
augment = Compose([
    TimeStretch(min_rate = 0.8, max_rate = 1.25, p = 0.7),
    TimeMask(min_band_part = 0.1, max_band_part = 0.2, p = 0.7),
    HighPassFilter(min_cutoff_freq=100, max_cutoff_freq=1000, p = 0.5),
    AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.008, p=1.0),
    RoomSimulator(p=0.5)
])

# Applying transformations to the audios
max_samples = 5000

while max_samples > len(os.listdir(path_augmented)):
  audio = random.choice(os.listdir(path_audios)) # Pick a random audio from the folder with the audios
  samples, sample_rate = librosa.load(path_audios+audio)
  augmented_signal = augment(samples = samples, sample_rate = sample_rate)
  sf.write(audio.split('.')[0]+f'-augmented{len(os.listdir(path_augmented))-len(os.listdir(path_audios))+1}.wav', augmented_signal, sample_rate)
  move(audio.split('.')[0]+f'-augmented{len(os.listdir(path_augmented))-len(os.listdir(path_audios))+1}.wav', path_augmented) # Move the new audio in the augmented folder
  if len(os.listdir(path_augmented)) % 500 == 0:
    print(f"Audios have been augmented to {len(os.listdir(path_augmented))} samples")

len(os.listdir('/content/audios-augmented'))

os.makedirs('/content/gdrive/MyDrive/DSIM_Project_Monochannelsignal/augmented_audios')

for audio in os.listdir(path_augmented):
  move(path_augmented+audio, '/content/gdrive/MyDrive/DSIM_Project_Monochannelsignal/augmented_audios')
  if len(os.listdir('/content/gdrive/MyDrive/DSIM_Project_Monochannelsignal/augmented_audios')) % 500 == 0:
    print(f"Succesfully uploaded {len(os.listdir('/content/gdrive/MyDrive/DSIM_Project_Monochannelsignal/augmented_audios'))} audios on Google Drive")