# -*- coding: utf-8 -*-
"""DataRetrieving_DSIM_Project_Monochannelsignal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbDtsYzS-nrsl3tUTNASt76P4KNfs5tt
"""

pip install kaggle

import os
os.environ["KAGGLE_CONFIG_DIR"] = '/content'

"""# **Data Collecting Through Kaggle API**"""

!kaggle datasets download -d uwrfkaggler/ravdess-emotional-speech-audio

"""Filename identifiers

* Modality (01 = full-AV, 02 = video-only, 03 = audio-only).

* Vocal channel (01 = speech, 02 = song).

* Emotion (01 = neutral, 02 = calm, 03 = happy, 04 = sad, 05 = angry, 06 = fearful, 07 = disgust, 08 = surprised).

* Emotional intensity (01 = normal, 02 = strong). NOTE: There is no strong intensity for the 'neutral' emotion.

* Statement (01 = "Kids are talking by the door", 02 = "Dogs are sitting by the door").

* Repetition (01 = 1st repetition, 02 = 2nd repetition).

* Actor (01 to 24. Odd numbered actors are male, even numbered actors are female).
"""

!unzip \*.zip && rm *.zip

import shutil
!mkdir audios
path ='/content/'

for dir in os.listdir(path+ 'audio_speech_actors_01-24'):
  for audio in os.listdir(path+dir):
    shutil.move(path+dir+'/'+audio, path +'audios')
  shutil.rmtree(path+dir)
shutil.rmtree(path+'audio_speech_actors_01-24')

len(os.listdir(path+'audios'))

from google.colab import drive
drive.mount('/content/gdrive')
!cp -r /content/audios /content/gdrive/MyDrive/

df